### ISSUE TITLE
Collect node metrics

### ISSUE THREAD

**Issue by razvan** [stackabletech/monitoring-operator#8]
## The problem

 Node metrics (cpu, mem, etc.) are currently not collected.

## Proposed solution

Install and manage a Prometheus node exporter. Implement using an additional role in the `monitoring-operator`.

## Alternate proposal : DaemonSet

Example for Prometheus node exporter. This has been tested using `microk8s` and the stackable agent started with `--hostname localhost` : 

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    kubernetes.io/os: stackable-linux
  name: node-exporter
  namespace: default
spec:
  selector:
    matchLabels:
      kubernetes.io/os: stackable-linux
  template:
    metadata:
      labels:
        kubernetes.io/os: stackable-linux
    spec:
      containers:
      - command:
        - node_exporter-1.2.0.linux-amd64/node_exporter
        - --web.listen-address=127.0.0.1:9100
        - --no-collector.wifi
        - --no-collector.hwmon
        - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)
        - --collector.netclass.ignored-devices=^(veth.*|[a-f0-9]{15})$
        - --collector.netdev.device-exclude=^(veth.*|[a-f0-9]{15})$
        image: node-exporter:1.2.0
        name: node-exporter
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: stackable-linux
      tolerations:
        - operator: Exists
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
    type: RollingUpdate
```

Issues with this approach:
* Doesn't work in the test-dev-cluster because there is no control plane available (k3s cannot start it in docker)
* The monitoring operator needs to be redesigned? What functionality will it cover ?
